"""Add sensitive data fields to File model

Revision ID: 5853e4cd726b
Revises: 
Create Date: 2025-06-05 19:06:18.326893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5853e4cd726b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_sensitive_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sensitive_data_types', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('sensitive_data_types')
        batch_op.drop_column('has_sensitive_data')

    # ### end Alembic commands ###
